### PR TITLE
Milestone 6: Friendships v2

### PR DESCRIPTION
**Pull request by zhuchini**
The instruction of this milestone is telling me to implement friendships with 2 rows for mutual friendship.
I believe it's about adding user_id and friend_id into my friendship table? I'm not quite sure.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @zhuchini :high_brightness: 

What you are referring to in the PR description is that:

- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

Which I believe you already implemented in your model, anyhow:

- [ ] You should define tests  for that requirement and also for the rest of your models

- [ ] We should have a notification of friendship and be able to accept/reject friendship requests (I can't see them)

- [ ] In the timeline we should be able to see our own posts and the posts of our friends.

Please :pray:  work on those and submit back for another review.

-----------------------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

**Comment by zhuchini** [comment]
Implemented the necessary changes:
- Defined tests;
- Fixed notification when adding/declining friend requests;
- Show posts only from the owner and friends.

**Comment by zhuchini** [comment]
- Implemented unit and integration tests for each model;
- Added an 'if' statement in the posts view file to show only friends and current_user's posts.
<article class="timeline">
  <% if current_user.friend?(@user) %>
    <h3>
      Recent posts
    </h3>
    <ul class="posts">
      <%= render 'posts/post' %>
    </ul>
  <% end %>
</article>

**Comment by zhuchini** [comment]
- Modified posts_controller to show only current_user's and friends' posts only;
- Implemented integration tests.

**Pull request merged**
